a = input("Enter the first fruite name : ")
b = input("Enter the second fruite name : ")
c = input("Enter the third fruite name : ")
d = input("Enter the fourth fruite name : ")
e = input("Enter the fifth fruite name : ")
f = input("Enter the sixth fruite name : ")
g = input("Enter the seventh fruite name : ")
list1 = []
list1.append(a)
list1.append(b)
list1.append(c)
list1.append(d)
list1.append(e)
list1.append(f)
list1.append(g)
print(list1)
